# Site settings
title: Kobol Blog
header-img: img/home-bg.jpg
email: contact@kobol.io
copyright_name: Kobol Team
description: "Helios4 Blog. The Open Source and Open Hardware NAS"
url: "https://blog.kobol.io"
github_username: helios-4
facebook_username: kobol.io
email_username: contact@kobol.io
comments: true

# Google Analytics
google_tracking_id: UA-96982596-2

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","Gemfile*"]

gems: [jekyll-paginate, jekyll-feed]
